import test from "node:test";
import assert from "node:assert/strict";
import { defaultBusinessPreferences } from "@localito/shared";
import { MemoryRepository } from "../apps/api/src/repository.js";
import { store } from "../apps/api/src/store.js";
import { parsePreferences, validProductImage } from "../apps/api/src/businessPreferences.js";
import { planReplenishment } from "../apps/web/src/lib/replenishment.js";

test("business settings reject invalid combinations and image payloads", () => {
  assert.deepEqual(parsePreferences(defaultBusinessPreferences), defaultBusinessPreferences);
  assert.throws(() => parsePreferences({ ...defaultBusinessPreferences, paymentMethods: ["mixed"] }));
  assert.throws(() => parsePreferences({ ...defaultBusinessPreferences, leadDays: -1 }));
  assert.throws(() => parsePreferences({ ...defaultBusinessPreferences, paymentMethods: [] }));
  assert.throws(() => parsePreferences({ ...defaultBusinessPreferences, bank: {} }));
  assert.equal(validProductImage("data:image/svg+xml;base64,AAAA"), false);
  assert.equal(validProductImage("javascript:alert(1)"), false);
  assert.equal(validProductImage("data:image/png;base64,AAAA"), true);
  assert.equal(validProductImage("data:image/png;base64," + "A".repeat(700000)), false);
});

test("tenant isolation, photo replacement/removal, idempotent sales, debt cash and overnight closing", async () => {
  const repo = new MemoryRepository();
  const { tenant, user } = await repo.registerTenant({ name: "QA", email: `qa-${Date.now()}@test.local`, password: "TestPassword123", businessName: "QA", businessType: "Test" });
  const preferences = parsePreferences({ ...defaultBusinessPreferences, paymentMethods: ["card", "cash"] });
  await repo.updateTenant(tenant.id, { preferences });
  assert.deepEqual((await repo.bootstrap(tenant.id)).tenant.preferences, preferences);
  const product = await repo.createProduct(tenant.id, { name: "QA", category: "QA", salePrice: 1000, costPrice: 500, stock: 100, minimumStock: 2, imageUrl: "data:image/png;base64,AAAA" });
  await repo.updateProduct(tenant.id, product.id, { imageUrl: "data:image/webp;base64,BBBB" });
  assert.equal((await repo.getProducts(tenant.id))[0].imageUrl, "data:image/webp;base64,BBBB");
  assert.equal(await repo.updateProduct("another-tenant", product.id, { imageUrl: "" }), null);
  await repo.updateProduct(tenant.id, product.id, { imageUrl: "" });
  assert.equal((await repo.getProducts(tenant.id))[0].imageUrl, undefined);
  const session = await repo.openCashSession(tenant.id, 10000, user.id);
  session.openedAt = new Date(Date.now() - 2 * 86400000).toISOString();
  const payload = { paymentMethod: "cash" as const, sellerId: user.id, idempotencyKey: "same-key", items: [{ productId: product.id, quantity: 2 }] };
  const [sale, duplicate] = await Promise.all([repo.createSale(tenant.id, payload), repo.createSale(tenant.id, payload)]);
  assert.equal(sale.id, duplicate.id);
  assert.equal(product.stock, 98);
  sale.createdAt = new Date(Date.now() - 86400000).toISOString();
  const customer = await repo.createCustomer(tenant.id, { name: "Customer", creditLimit: 20000 });
  await repo.createSale(tenant.id, { paymentMethod: "credit", sellerId: user.id, customerId: customer.id, items: [{ productId: product.id, quantity: 4 }] });
  await repo.payCustomerDebt(tenant.id, customer.id, 1000, "cash");
  await repo.addCashMovement(tenant.id, { type: "expense", amount: 500, reason: "Expense", userId: user.id });
  await repo.addCashMovement(tenant.id, { type: "withdrawal", amount: 200, reason: "Withdrawal", userId: user.id });
  await repo.addCashMovement(tenant.id, { type: "deposit", amount: 300, reason: "Deposit", userId: user.id });
  const summary = await repo.getCashRegister(tenant.id);
  assert.equal(summary.expectedCash, 12600);
  await assert.rejects(repo.closeCashSession(tenant.id, 12500, undefined, user.id), /obligatorio/);
  assert.equal((await repo.getOpenCashSession(tenant.id))?.status, "open");
  const closed = await repo.closeCashSession(tenant.id, 12500, "Diferencia contada", user.id);
  assert.equal(closed?.expectedCash, 12600);
  assert.equal(closed?.difference, -100);
  assert.equal((await repo.getPayments(tenant.id)).length, 1);
  assert.equal((await repo.getPayments("another-tenant")).length, 0);
  assert.equal((await repo.getDebts(tenant.id))[0].balance, 3000);
  const recentSale = { ...sale, createdAt: new Date().toISOString(), items: [{ ...sale.items[0], quantity: 30 }] };
  const forecast = planReplenishment([{ ...product, stock: 1 }], [recentSale], [], 3, 14);
  assert.equal(forecast[0].quantity, 16);
  const incoming = [{ id: "order", tenantId: tenant.id, supplierId: "supplier", status: "partially_received" as const, total: 1, createdAt: new Date().toISOString(), items: [{ productId: product.id, quantity: 10, receivedQuantity: 2, unitCost: 500, subtotal: 5000 }] }];
  assert.equal(planReplenishment([{ ...product, stock: 1 }], [recentSale], incoming, 3, 14)[0].quantity, 8);
  assert.equal(planReplenishment([product], [], [], 3, 14)[0].slow, true);
  assert.equal(store.sales.filter(entry => entry.tenantId === tenant.id).length, 2);
});
