name: Prueba runner documental

on:
  push:
    branches:
      - docs/reorganizacion-integral-2026-10-03

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prueba
        run: echo "runner disponible"
